# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Validation
  jobs:
  - job: Validation
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Validation
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'Free Trial(1)(93a0beb1-d22d-4f41-9106-f3a61eb90b89)'
        subscriptionId: '93a0beb1-d22d-4f41-9106-f3a61eb90b89'
        location: 'Central US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/**/ArmTemplates/webapp-template.json'
        csmParametersFile: '$(Pipeline.Workspace)/**/ArmTemplates/parameters.json'
        deploymentMode: 'Validation'

